name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build site
        uses: withastro/action@v2
        with:
          package-manager: pnpm@latest

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --base dist --exclude-all-private dist
          fail: True

      - name: Create Issue From File
        if: github.repository_owner == 'lycheeverse' && env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
